### ISSUE TITLE
H2 Mod Error at the end of Whiskey Hotel

### ISSUE THREAD

**Issue by Louis-Mont** [Loyalists/gflh2#2]
Got an error at the end of Whiskey Hotel, just when the dark screen pops, I launched the mission in H2-Mod without any mods and it worked just fine

![whiskeyhotel](https://user-images.githubusercontent.com/62873594/228317314-ee418259-9c91-4ee0-9e29-b1347abc32b4.png)

Edit : I have H2 Mod up to date, Nvidia drivers and Windows 10 as well

**Comment by 68595959** [comment]
It looks like it also crashes when launching other mods. This is already the standard.

**Comment by Loyalists** [comment]
This is one of the [known issues](https://github.com/Loyalists/gflh2/wiki/Known-Issues) and according to the last comment it doesn't relate to the gfl mod :)
