### ISSUE TITLE
运行h2-mod.exe错误，需要更新显卡驱动和系统更新

### ISSUE THREAD

**Issue by HibikiLuler** [Loyalists/gflh2#3]
弹窗错误如下：
Fatal error (Oxco000005) at Ox00007FFB9F9D5E16.A minidump has been written.
Make sure to update your graphics card drivers and install operatingsystem updates!
[h2-mod-crash-1-2023-05-29-04-22-21.zip](https://github.com/Loyalists/gflh2/files/11585647/h2-mod-crash-1-2023-05-29-04-22-21.zip)
但我已经保证显卡驱动为最新，系统是win10 19041.264

**Comment by Loyalists** [comment]
https://github.com/Loyalists/gflh2/wiki/Known-Issues
在画质设置中关闭Shader Preload
